version: '3.7'
services:
  api:
    build: .
    image: voce-sabia-api-v1
    ports:
      - "3000:3000"
      
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: events
    ports:
      - 5432:5432
